version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 3005:5432
    volumes:
      - ./PostgreSQL/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=mmo
      - POSTGRES_DB=nextjs-prisma
